#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: payment-routing-service
  datasource:
    url: jdbc:h2:mem:payments_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true

server:
  port: 8080

provider:
  retry:
    max-attempts: 3
    backoff:
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000
  endpoints:
    provider-a: http://localhost:8081/api/v1/payments
    provider-b: http://localhost:8082/api/v1/payments

outbox:
  processing:
    enabled: true
    fixed-delay: 5000
    max-attempts: 5

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html